version: "3"
services: 
    server:
        build: .
        ports: 
            - 5000:5000
        depends_on: 
            - postgres
            - redis

    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: bus-test
        healthcheck:
            test: ['CMD-SHELL', 'pg_is ready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always
        volumes: 
            - ../data/pg-data:/var/libs/postgresql/data
        ports: 
            - 5432:5432
        
    redis:
        image: redis:alpine
        hostname: redis
        restart: always
        volumes: 
            - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
        ports: 
            - 6379:6379
     